-- Remediation for: [HIGH] Data quality incident on healthcare.raw_patients
-- Generated by ML Guardian from DataHub metadata.
--
-- Planted validity violations on raw_patients: negative billing (~2%),
-- out-of-range age (~1.5%), swapped admission/discharge dates (~0.5%),
-- null names (~1%). These silently bias the downstream readmission_risk model.
--
-- Purpose: fail the load when any validity rule is violated above tolerance.

SELECT
    SUM(CASE WHEN billing_amount < 0 THEN 1 ELSE 0 END)                       AS negative_billing,
    SUM(CASE WHEN age < 0 OR age > 120 THEN 1 ELSE 0 END)                     AS invalid_age,
    SUM(CASE WHEN discharge_date < date_of_admission THEN 1 ELSE 0 END)       AS swapped_dates,
    SUM(CASE WHEN name IS NULL OR name = '' THEN 1 ELSE 0 END)                AS null_name,
    COUNT(*)                                                                  AS total_rows
FROM healthcare.raw_patients
HAVING negative_billing > 0
    OR invalid_age > 0
    OR swapped_dates > 0
    OR CAST(null_name AS FLOAT) / total_rows > 0.005;

-- A returned row means one or more validity gates failed: stop the feature build
-- and notify the data owner before the model consumes bad records.
