-- Remediation for: [CRITICAL] Freshness incident on nyc_taxi.staging_trips
-- Generated by ML Guardian from DataHub metadata (SQLite pipeline, SLA = 24h).
--
-- Root cause: staging_trips stopped ~3 days before raw_trips' max date, while
-- ingestion metadata still looks recent -- a silent staleness that naive freshness
-- checks miss. Downstream mart_daily_summary -> fare_prediction_model then score on
-- stale data.
--
-- Purpose: fail the pipeline early when staging lags its source.

SELECT
    MAX(tpep_pickup_datetime) AS last_loaded_at,
    (JULIANDAY('now') - JULIANDAY(MAX(tpep_pickup_datetime))) * 24 AS hours_stale
FROM nyc_taxi.staging_trips
HAVING (JULIANDAY('now') - JULIANDAY(MAX(tpep_pickup_datetime))) * 24 > 24;

-- Stronger check: assert staging is not lagging raw by more than one day.
-- SELECT (JULIANDAY((SELECT MAX(tpep_pickup_datetime) FROM nyc_taxi.raw_trips))
--       - JULIANDAY((SELECT MAX(tpep_pickup_datetime) FROM nyc_taxi.staging_trips)))
--       AS staging_lag_days;  -- alert if > 1
